GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta"
GEMINI_API_KEY = "AIzaSyB9pkHQUgrlQApdsQyLJEzqC71rUgqL7Cs"
PG_CONN_STRING = "postgresql://postgres:postgres@localhost:5432/regulations"
EMBEDDING_MODEL = "models/embedding-001"
CHAT_MODEL = "models/gemini-pro"
